### PR TITLE
sumDIGIT done

### PR DESCRIPTION
**Pull request by infernus01**

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Run the test case first!

**Comment by Anamaya1729** [comment]
Don't SPAM the PR's this is the warning.

**Comment by infernus01** [comment]
> Don't SPAM the PR's this is the warning.

I've just done the tasks and created PRs accordingly....and This is not spamming

**Comment by Anamaya1729** [comment]
You haven't completed any single task correctly. Did you even read a single README? Creating 14 PR! without reading anything is spamming.

**Comment by Anamaya1729** [comment]
Completed in #22

**Pull request closed without merging**
