### PR TITLE
solution.py

### PR DESCRIPTION
**Pull request by ashirvadpandey**

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Thanks for contributing, but your solution does not passes all the test cases. Please run `tests.py` file.

**Comment by ashirvadpandey** [comment]
I have all the test cases manually and all are passing ...if you have any test case please type 
i will to correct my code

**Comment by Anamaya1729** [comment]
There are some issues with the code that I would like to address:
1.  Please read the `README.md` file for this problem, thoroughly.
2.  In the test file your function `solution` is tested, by passing an unsorted array to the function, however your submitted code doesn't take any arguments.
3. There is syntax error on line 5.
4. And  lastly please run `tests.py` file. Before committing your code again.

**Comment by ashirvadpandey** [comment]
updated ....please check

**Comment by Anamaya1729** [comment]
1. There is indentation error.
2. Line 9 and 10 are not necessary.
3. Bubble sort logic is incorrect.
4. Please run your code, test your code before commiting.

**Comment by ashirvadpandey** [comment]
updated ...please check

**Review by Anamaya1729 — COMMENTED** [review]
Your code is failing Exception Test 3 and Exception test 4.

**Comment by ashirvadpandey** [comment]
i have checked these test case ,given in test.py. and all are passing successfully 
[1, 2, 3, 4, ]
[5, 4, 3, 2, 1]
[1, 3, 5, 2, 4]
[1, 3, 5, 2, 4, 6, 8, 7]
[1, 3, 5, 2, 4, 6, 8, 7, 9]
[1, 3, 5, 2, 4, 6, 8, 7, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
["b", "c", "l", "a", "z"]
["b", "c", "l", "a", "z", "a", "b", "c", "l", "z"]

**Pull request closed without merging**
