### PR TITLE
Fibonacci using recurion...all the test cases passed

### PR DESCRIPTION
**Pull request by infernus01stronger**
It has passed all the test cases

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Hey, thanks for contribution, please run the test cases. Don't change the function name, test cases need the function name to be solution. line 6 and 7 are not needed. Run the file tests using command `python3 tests.py`.Make changes in your commit and If it passes all test then submit your PR.

**Comment by infernus01stronger** [comment]
> Hey, thanks for contribution, please run the test cases. Don't change the function name, test cases need the function name to be solution. line 6 and 7 are not needed. Run the file tests using command `python3 tests.py`.Make changes in your commit and If it passes all test then submit your PR.

but the readme says to create a function with name 'answer'...and for the lines, I'd say only 4th was not needed I guess...if I won't take input according to readme, how would I suppose to print the answer in the form of an unknown variable?

**Comment by Anamaya1729** [comment]
Well that was a mistake, thanks for pointing it out.  I'll correct it. Your Inputs and output will be automatically tested. Please run `tests.py` file.

**Comment by Anamaya1729** [comment]
Thanks for the contribution!

**Pull request merged**
