### PR TITLE
Implementation of Binary search.

### PR DESCRIPTION
**Pull request by thechangamunda**
Implementation of Binary search with and without recursion.

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Don't change the function name. Run the test by running `tests.py` make sure all tests pass. Implement only one solution at a time, either iterative or recursive.

**Comment by thechangamunda** [comment]
Okay, I'll work on the recursive one then.

**Comment by Anamaya1729** [comment]
You are still making changes in other file, remove that change and commit.

**Review by thechangamunda — COMMENTED** [review]
I have updated them but I am not able to merge it.
checks

**Comment by thechangamunda** [comment]
> You are still making changes in other file, remove that change and commit.

Okay

**Comment by Anamaya1729** [comment]
Remove changes in `binary_search/solution.py` then commit.

**Comment by Anamaya1729** [comment]
You don't have to make any changes in it, not to default or anything. Its solution is already merged, so it cannot go back to default, just remove the changes done in it, then commit!

**Comment by thechangamunda** [comment]
I removed the changes I made in binary_search/solution.py and tried to commit.
I have applied the solution that you provided in the binary_search_recursion/solution.py

**Comment by thechangamunda** [comment]
I am sorry for creating a confusion, I am fairly new with the  open source, 
What I have to do is remove my solution from binary_search/solution.py, right?

**Pull request closed without merging**
