### PR TITLE
Update solution.py

### PR DESCRIPTION
**Pull request by Suhas2002**

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Thanks for the contribution. Please run the `tests.py` file and make sure all the test cases passes in it. Code below line 27 is not required since only function is required.

**Review by Suhas2002 — COMMENTED** [review]
I have made the changes, please check

**Comment by Anamaya1729** [comment]
It still doesn't passes all the test cases.

**Comment by Suhas2002** [comment]
Yeah working on it

**Comment by Anamaya1729** [comment]
We are merging only one PR per account, since #50 is already merged please contribute in the other repositories to support open source cause. If you still want to contribute you can contribute after the end of Hacktoberfest.

**Pull request closed without merging**
