### PR TITLE
Implement Binary Search.

### PR DESCRIPTION
**Pull request by thechangamunda**

### CODE REVIEW

**Comment by thechangamunda** [comment]
I synced this repo into my repo and all the changes were lost, I have made the changes as you asked can you please go through them.
Sorry for creating the confusion, it's my first time contributing in open source.

**Comment by thechangamunda** [comment]
@Anamaya1729

**Comment by Anamaya1729** [comment]
image
In the file-changed section of your pull request you can see you are trying to make changes in 3 files. 
- First one is the `easy/binary_search/solution.py` where someone else code is already written and your change is to remove it all.
- Second change is correct change you are trying to create.
- Third is temp runner file that you have added with your code that is not needed.

It's fine you will learn by doing mistakes and it is the safe space to do it. Try to solve the above problems and create a pull request with only required changes.

**Comment by thechangamunda** [comment]
So, I have to remove the temp file that I have added.

**Comment by thechangamunda** [comment]
And the changes done by me in the ``` binary_search/solution.py```, I have to change it to the on present in the current repository.
@Anamaya1729

**Comment by Anamaya1729** [comment]
Yes! You understood it!

**Review by Anamaya1729 — APPROVED** [review]

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Your solution is not recurcive now.

**Comment by thechangamunda** [comment]
On it, my bad.

**Comment by Anamaya1729** [comment]
It fails the test, where target is not present in the list, its returning None it should return -1.

**Review by Anamaya1729 — APPROVED** [review]

**Comment by thechangamunda** [comment]
Thankyou for your patience. 
I learned a lot ʕ •ᴥ•ʔゝ☆.

**Pull request merged**
